# Generated by Django 3.2.9 on 2022-01-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Deivice_Name', models.CharField(max_length=30)),
                ('Device_Model', models.CharField(max_length=30)),
                ('Production_Year', models.DateField(auto_now=True)),
                ('IMEIL', models.IntegerField(max_length=15)),
                ('Produced_By', models.CharField(max_length=100)),
            ],
        ),
    ]
